services:
  upsnap:
    ports:
      - 8090:8090
    container_name: upsnap
    image: seriousm4x/upsnap:5
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    network_mode: host
    labels:
      homepage.group: "Tools"
      homepage.name: "Upsnap"
      homepage.icon: "upsnap.png"
      homepage.description: "Wake On Lan"
      homepage.href: "http://100.119.64.85:8090"
      homepage.siteMonitor: "http://100.119.64.85:8090"
